services:
  backend:
    build: .
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

  worker:
    build: .
    env_file:
      - .env
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped