services:
  backend:
    build: .
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: image_redis
    ports:
      - "6379:6379"