# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_backup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_manual = QtWidgets.QLabel(self.centralwidget)
        self.label_manual.setGeometry(QtCore.QRect(0, 0, 800, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_manual.setFont(font)
        self.label_manual.setStyleSheet("background-color: rgb(150, 150, 150);\n"
"color: rgb(255, 255, 255);")
        self.label_manual.setObjectName("label_manual")
        self.btn_pack = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pack.setGeometry(QtCore.QRect(700, 100, 75, 23))
        self.btn_pack.setStyleSheet("background-color: rgb(148, 255, 148);")
        self.btn_pack.setObjectName("btn_pack")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(700, 150, 75, 23))
        self.btn_cancel.setObjectName("btn_cancel")
        self.label_success = QtWidgets.QLabel(self.centralwidget)
        self.label_success.setGeometry(QtCore.QRect(0, 200, 800, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_success.setFont(font)
        self.label_success.setStyleSheet("background-color: rgb(150, 150, 150);\n"
"color: rgb(255, 255, 255);")
        self.label_success.setObjectName("label_success")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Бекап базы"))
        self.label_manual.setText(_translate("MainWindow", "Перед тем, как сделать резервную копию базы данных, убедитесь что:\n"
"- программа закрыта;\n"
"- все необходимые внешние носители подключены."))
        self.btn_pack.setText(_translate("MainWindow", "Упаковать"))
        self.btn_cancel.setText(_translate("MainWindow", "Закрыть"))
        self.label_success.setText(_translate("MainWindow", "Резервная копия базы данных успешно создана!"))

    def add_functions(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
